steps:
  - name: build-and-push
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u allenday --password-stdin
      - docker build -t ghcr.io/relayos/kiwiirc:${CI_COMMIT_SHA:0:8} .
      - docker build -t ghcr.io/relayos/kiwiirc:latest .
      - docker push ghcr.io/relayos/kiwiirc:${CI_COMMIT_SHA:0:8}
      - docker push ghcr.io/relayos/kiwiirc:latest

when:
  event: push
  branch: master
